// crypto.test.js — the cryptographic protocol (SPEC.md).
// Runs in the real workerd runtime (vitest-pool-workers): Web Crypto,
// CompressionStream, and AES-256-GCM behave as in production.
import { describe, it, expect } from 'vitest';
import {
  encryptPaste, decryptPaste, deriveContentKey, decryptContent,
  deriveKEK, aesGcmEncrypt, aesGcmDecrypt,
  gzip, gunzip, PasswordRequired, DecryptError, MAX_PLAINTEXT,
} from '../public/js/crypto.js';
import { buildAAD, validatePaste } from '../public/js/format.js';
import { hex, b64urlFromBytes, bytesFromB64url, randomBytes, utf8, fromUtf8 } from '../public/js/bytes.js';

const seq = (start, n) => Uint8Array.from({ length: n }, (_, i) => (start + i) & 0xff);
const fill = (v, n) => new Uint8Array(n).fill(v);
const unhex = (h) => Uint8Array.from(h.match(/../g).map((b) => parseInt(b, 16)));

// ── Fixed inputs shared by the frozen vectors (SPEC.md §11) ──────────────────
const F = seq(0, 32);
const CEK = seq(0x20, 32);
const ivc = fill(0x11, 12);
const ivw = fill(0x22, 12);
const salt = fill(0x33, 16);
const VEC_PLAINTEXT = 'binthere vector — zero knowledge ✓';

// FROZEN vectors — generated by test/genvectors.mjs and pinned here. Any change
// to the protocol MUST update SPEC.md and regenerate these deliberately.
const VECTORS = {
  nopw: {
    adata: { alg: 'A256GCM', kdf: 'hkdf', iter: 0, comp: 'none', fmt: 'plaintext', bar: false,
             ivc: b64urlFromBytes(ivc), ivw: b64urlFromBytes(ivw), skdf: '' },
    usePassword: false, password: '', iter: 0,
    aadHex: '62696e74686572652f76310a616c673d4132353647434d0a6b64663d686b64660a697465723d300a636f6d703d6e6f6e650a666d743d706c61696e746578740a6261723d300a6976633d455245524552455245524552455245520a6976773d496949694969496949694969496949690a736b64663d0a',
    wkHex: '07adc270949ba48117e0553655023ae11d326766c13f9dc06b05a69085f5306bd0de61efac880cc08a63ac800daf2a39',
    ctHex: '51541cd10292619073e3adbab99d55c8839d57470ec512ba5d5edc785ab314316870323b42928ccf3cf019e7d978e06397fe19127efa',
  },
  pw: {
    adata: { alg: 'A256GCM', kdf: 'pbkdf2-hkdf', iter: 310000, comp: 'none', fmt: 'plaintext', bar: false,
             ivc: b64urlFromBytes(ivc), ivw: b64urlFromBytes(ivw), skdf: b64urlFromBytes(salt) },
    usePassword: true, password: 'correct horse', iter: 310000,
    aadHex: '62696e74686572652f76310a616c673d4132353647434d0a6b64663d70626b6466322d686b64660a697465723d3331303030300a636f6d703d6e6f6e650a666d743d706c61696e746578740a6261723d300a6976633d455245524552455245524552455245520a6976773d496949694969496949694969496949690a736b64663d4d7a4d7a4d7a4d7a4d7a4d7a4d7a4d7a4d7a4d7a4d770a',
    wkHex: '7e725b2ac4e6e87e6611414186d6ae345f1350d6ab29a669d358009ea80c7b7e8b91f5bafd77d958339c236cd3aaa8a1',
    ctHex: '51541cd10292619073e3adbab99d55c8839d57470ec512ba5d5edc785ab314316870323b42926928351131f61f1f667f678bf05521e4',
  },
};

describe('frozen test vectors', () => {
  for (const [name, v] of Object.entries(VECTORS)) {
    it(`${name}: canonical AAD matches`, () => {
      expect(hex(buildAAD(v.adata))).toBe(v.aadHex);
    });
    it(`${name}: CEK wrap matches and unwraps`, async () => {
      const aad = buildAAD(v.adata);
      const kek = await deriveKEK(F, { usePassword: v.usePassword, password: v.password, salt, iter: v.iter });
      const wk = await aesGcmEncrypt(kek, ivw, CEK, aad);
      expect(hex(wk)).toBe(v.wkHex);
      expect(hex(await aesGcmDecrypt(kek, ivw, wk, aad))).toBe(hex(CEK));
    });
    it(`${name}: content ciphertext matches and decrypts`, async () => {
      const aad = buildAAD(v.adata);
      const key = await crypto.subtle.importKey('raw', CEK, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt']);
      const ct = await aesGcmEncrypt(key, ivc, utf8(VEC_PLAINTEXT), aad);
      expect(hex(ct)).toBe(v.ctHex);
      expect(fromUtf8(await aesGcmDecrypt(key, ivc, unhex(v.ctHex), aad))).toBe(VEC_PLAINTEXT);
    });
  }
});

describe('encrypt/decrypt round-trip', () => {
  it('no-password round-trips and emits a valid format-v1 body', async () => {
    const text = 'hello, binthere';
    const { body, fragment } = await encryptPaste({ text });
    expect(() => validatePaste(body)).not.toThrow();
    expect(body.adata.kdf).toBe('hkdf');
    const out = await decryptPaste({ paste: body, fragment });
    expect(out.text).toBe(text);
  });

  it('round-trips every format and the burn flag', async () => {
    for (const fmt of ['plaintext', 'code', 'markdown']) {
      for (const bar of [false, true]) {
        const text = `body ${fmt} ${bar}`;
        const { body, fragment } = await encryptPaste({ text, fmt, bar });
        const out = await decryptPaste({ paste: body, fragment });
        expect(out).toEqual({ text, fmt, bar });
      }
    }
  });

  it('the fragment secret never appears in the POST body', async () => {
    const { body, fragment } = await encryptPaste({ text: 'secret' });
    expect(JSON.stringify(body)).not.toContain(fragment);
  });
});

describe('password key hierarchy (SPEC.md §2)', () => {
  it('decrypts only with the correct fragment AND password', async () => {
    const text = 'top secret';
    const password = 'hunter2';
    const { body, fragment } = await encryptPaste({ text, password });
    expect(body.adata.kdf).toBe('pbkdf2-hkdf');
    const out = await decryptPaste({ paste: body, fragment, password });
    expect(out.text).toBe(text);
  });

  it('fragment alone is insufficient (no password → PasswordRequired)', async () => {
    const { body, fragment } = await encryptPaste({ text: 'x', password: 'pw' });
    await expect(decryptPaste({ paste: body, fragment })).rejects.toBeInstanceOf(PasswordRequired);
    await expect(decryptPaste({ paste: body, fragment, password: 'wrong' })).rejects.toBeInstanceOf(DecryptError);
  });

  it('password alone is insufficient (wrong fragment → DecryptError)', async () => {
    const { body, password } = { ...(await encryptPaste({ text: 'x', password: 'pw' })), password: 'pw' };
    const wrongFragment = b64urlFromBytes(fill(0x99, 32));
    await expect(decryptPaste({ paste: body, fragment: wrongFragment, password })).rejects.toBeInstanceOf(DecryptError);
  });
});

describe('deriveContentKey / decryptContent split (verify before consume)', () => {
  it('verifies the password independently of the content, then decrypts', async () => {
    const { body, fragment } = await encryptPaste({ text: 'split me', password: 'pw' });
    const cek = await deriveContentKey({ adata: body.adata, wk: body.wk, fragment, password: 'pw' });
    expect((await decryptContent({ adata: body.adata, ct: body.ct, cek })).text).toBe('split me');
  });

  it('throws on wrong password and PasswordRequired without one — without touching ct', async () => {
    const { body, fragment } = await encryptPaste({ text: 'x', password: 'pw' });
    await expect(deriveContentKey({ adata: body.adata, wk: body.wk, fragment, password: 'bad' }))
      .rejects.toBeInstanceOf(DecryptError);
    await expect(deriveContentKey({ adata: body.adata, wk: body.wk, fragment }))
      .rejects.toBeInstanceOf(PasswordRequired);
  });
});

describe('authentication / tamper (AAD + ciphertext binding)', () => {
  async function make() {
    return encryptPaste({ text: 'authentic', fmt: 'plaintext', bar: false });
  }
  it('flipping an authenticated adata field breaks decryption', async () => {
    for (const mutate of [
      (b) => { b.adata.bar = true; },
      (b) => { b.adata.fmt = 'markdown'; },
      (b) => { b.adata.comp = b.adata.comp === 'gzip' ? 'none' : 'gzip'; },
    ]) {
      const { body, fragment } = await make();
      mutate(body);
      await expect(decryptPaste({ paste: body, fragment })).rejects.toBeInstanceOf(DecryptError);
    }
  });
  it('flipping a ciphertext byte breaks decryption', async () => {
    const { body, fragment } = await make();
    const ct = bytesFromB64url(body.ct);
    ct[0] ^= 0x01;
    body.ct = b64urlFromBytes(ct);
    await expect(decryptPaste({ paste: body, fragment })).rejects.toBeInstanceOf(DecryptError);
  });
  it('swapping the IV breaks decryption', async () => {
    const { body, fragment } = await make();
    body.adata.ivc = b64urlFromBytes(fill(0x00, 12));
    await expect(decryptPaste({ paste: body, fragment })).rejects.toBeInstanceOf(DecryptError);
  });
});

describe('compression', () => {
  it('compresses compressible content and round-trips', async () => {
    const text = 'x'.repeat(50000);
    const { body, fragment } = await encryptPaste({ text });
    expect(body.adata.comp).toBe('gzip');
    expect((await decryptPaste({ paste: body, fragment })).text).toBe(text);
  });

  it('rejects oversized plaintext before encryption', async () => {
    const big = 'a'.repeat(MAX_PLAINTEXT + 1);
    await expect(encryptPaste({ text: big })).rejects.toThrow(/too large/);
  });
});

describe('decompression safety', () => {
  it('aborts a gzip bomb that exceeds the output cap', async () => {
    const bomb = await gzip(fill(0, 200000)); // 200 KB of zeros → tiny gzip
    await expect(gunzip(bomb, 1000)).rejects.toBeInstanceOf(DecryptError);
  });
  it('rejects malformed gzip input', async () => {
    await expect(gunzip(fill(0xab, 64))).rejects.toBeInstanceOf(DecryptError);
  });
});

describe('base64url canonicity (SPEC §1 errata) — fail closed on aliasing encodings', () => {
  it('accepts the canonical encoding of every remainder length', () => {
    expect(Array.from(bytesFromB64url('Zg'))).toEqual([0x66]);        // rem 2
    expect(Array.from(bytesFromB64url('Zm8'))).toEqual([0x66, 0x6f]); // rem 3
    expect(Array.from(bytesFromB64url('Zm9v'))).toEqual([0x66, 0x6f, 0x6f]); // rem 0
    expect(Array.from(bytesFromB64url('AA'))).toEqual([0x00]);
    expect(Array.from(bytesFromB64url(''))).toEqual([]);
  });

  it('rejects non-canonical encodings (non-zero unused bits in the final char)', () => {
    // Each would silently alias the canonical string to the same bytes.
    for (const bad of ['Zh', 'AB', 'Zm9', 'AAB', 'A_', 'AA_']) {
      expect(() => bytesFromB64url(bad), bad).toThrow(/invalid base64url/);
    }
  });

  it('still rejects bad alphabet and impossible lengths', () => {
    for (const bad of ['Zg=', 'Z g', 'Zm9vY', 'a+b/', '%%%']) {
      expect(() => bytesFromB64url(bad), bad).toThrow(/invalid base64url/);
    }
  });

  it('round-trips: encode ∘ decode is the identity on canonical strings', () => {
    for (const s of ['', 'AA', 'Zg', 'Zm8', 'Zm9v', b64urlFromBytes(randomBytes(31))]) {
      expect(b64urlFromBytes(bytesFromB64url(s))).toBe(s);
    }
  });
});

describe('password NFC normalization (SPEC §2 errata)', () => {
  it('NFD and NFC forms of the same password derive the same key', async () => {
    const nfc = 'café';  // é as one code point
    const nfd = 'café'; // e + combining acute
    expect(nfc).not.toBe(nfd);      // distinct strings…
    const { body, fragment } = await encryptPaste({ text: 'across devices', password: nfd });
    // …but the paste created with the NFD input opens with the NFC input.
    const out = await decryptPaste({ paste: body, fragment, password: nfc });
    expect(out.text).toBe('across devices');
  });
});
