// genvectors.mjs — regenerate the FROZEN crypto test vectors pinned in
// test/crypto.test.js. Run with:  node test/genvectors.mjs
//
// The vectors freeze protocol v1 (SPEC.md §11) at the byte level: from a set of
// fixed inputs (F, CEK, IVs, salt, plaintext) it recomputes the canonical AAD,
// the wrapped CEK, and the content ciphertext for the no-password and password
// branches, then prints a ready-to-paste `VECTORS` object.
//
// This is a DELIBERATE, spec-first step. Any protocol/format/AAD change MUST
// update SPEC.md first, then rerun this to regenerate the vectors — never edit
// the pinned hexes by hand. See CONTRIBUTING.md.
//
// CI diffs this script's output against test/vectors.expected.txt byte-for-byte
// (.github/workflows/ci.yml). When regenerating, refresh both places:
//   node test/genvectors.mjs > test/vectors.expected.txt
// and paste the same output over the VECTORS object in test/crypto.test.js.
//
// It imports the same shared modules the browser and Worker use, and runs on
// Node's Web Crypto (Node 18+), so a conforming implementation reproduces the
// exact bytes committed in test/crypto.test.js.

import {
  deriveKEK, aesGcmEncrypt, aesGcmDecrypt,
} from '../public/js/crypto.js';
import { buildAAD } from '../public/js/format.js';
import { hex, b64urlFromBytes, utf8, fromUtf8 } from '../public/js/bytes.js';

// ── Fixed inputs shared by the frozen vectors (must match crypto.test.js) ────
const seq = (start, n) => Uint8Array.from({ length: n }, (_, i) => (start + i) & 0xff);
const fill = (v, n) => new Uint8Array(n).fill(v);

const F = seq(0, 32);
const CEK = seq(0x20, 32);
const ivc = fill(0x11, 12);
const ivw = fill(0x22, 12);
const salt = fill(0x33, 16);
const VEC_PLAINTEXT = 'binthere vector — zero knowledge ✓';

// The two branches the vectors cover (SPEC.md §11): no-password (HKDF only) and
// password-protected (PBKDF2 → HKDF). `iter`/`skdf` mirror what the format stores.
const CASES = {
  nopw: {
    adata: { alg: 'A256GCM', kdf: 'hkdf', iter: 0, comp: 'none', fmt: 'plaintext', bar: false,
             ivc: b64urlFromBytes(ivc), ivw: b64urlFromBytes(ivw), skdf: '' },
    usePassword: false, password: '', iter: 0,
  },
  pw: {
    adata: { alg: 'A256GCM', kdf: 'pbkdf2-hkdf', iter: 310000, comp: 'none', fmt: 'plaintext', bar: false,
             ivc: b64urlFromBytes(ivc), ivw: b64urlFromBytes(ivw), skdf: b64urlFromBytes(salt) },
    usePassword: true, password: 'correct horse', iter: 310000,
  },
};

async function computeVector(c) {
  const aad = buildAAD(c.adata);

  // Wrapped CEK: encrypt the CEK under the KEK derived from F (+ password).
  const kek = await deriveKEK(F, { usePassword: c.usePassword, password: c.password, salt, iter: c.iter });
  const wk = await aesGcmEncrypt(kek, ivw, CEK, aad);

  // Content ciphertext: encrypt the plaintext under the CEK.
  const contentKey = await crypto.subtle.importKey('raw', CEK, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt']);
  const ct = await aesGcmEncrypt(contentKey, ivc, utf8(VEC_PLAINTEXT), aad);

  // Self-check: the wrap unwraps back to the CEK and the ciphertext decrypts.
  const unwrapped = await aesGcmDecrypt(kek, ivw, wk, aad);
  if (hex(unwrapped) !== hex(CEK)) throw new Error('self-check failed: CEK unwrap mismatch');
  const decrypted = fromUtf8(await aesGcmDecrypt(contentKey, ivc, ct, aad));
  if (decrypted !== VEC_PLAINTEXT) throw new Error('self-check failed: content decrypt mismatch');

  return {
    adata: c.adata,
    usePassword: c.usePassword, password: c.password, iter: c.iter,
    aadHex: hex(aad),
    wkHex: hex(wk),
    ctHex: hex(ct),
  };
}

const q = (s) => `'${s}'`;

function printVector(name, v) {
  const a = v.adata;
  console.log(`  ${name}: {`);
  console.log(`    adata: { alg: ${q(a.alg)}, kdf: ${q(a.kdf)}, iter: ${a.iter}, comp: ${q(a.comp)}, fmt: ${q(a.fmt)}, bar: ${a.bar},`);
  console.log(`             ivc: b64urlFromBytes(ivc), ivw: b64urlFromBytes(ivw), skdf: ${a.skdf === '' ? "''" : 'b64urlFromBytes(salt)'} },`);
  console.log(`    usePassword: ${v.usePassword}, password: ${q(v.password)}, iter: ${v.iter},`);
  console.log(`    aadHex: ${q(v.aadHex)},`);
  console.log(`    wkHex: ${q(v.wkHex)},`);
  console.log(`    ctHex: ${q(v.ctHex)},`);
  console.log('  },');
}

const vectors = {};
for (const [name, c] of Object.entries(CASES)) vectors[name] = await computeVector(c);

console.log('// FROZEN vectors — generated by test/genvectors.mjs and pinned here. Any');
console.log('// change to the protocol MUST update SPEC.md and regenerate these deliberately.');
console.log('const VECTORS = {');
for (const [name, v] of Object.entries(vectors)) printVector(name, v);
console.log('};');
